/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9ff",
        "primary-fixed": "#9cf2e8",
        "on-secondary-fixed": "#341100",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3e4947",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004c69",
        "outline-variant": "#bdc9c6",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#006a63",
        "tertiary-container": "#007199",
        "secondary": "#9d4300",
        "inverse-primary": "#80d5cb",
        "on-tertiary-container": "#d4edff",
        "on-surface": "#0b1c30",
        "on-secondary-container": "#5c2400",
        "on-secondary-fixed-variant": "#783200",
        "inverse-surface": "#213145",
        "on-tertiary": "#ffffff",
        "outline": "#6e7977",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed-dim": "#ffb690",
        "primary-fixed-dim": "#80d5cb",
        "tertiary": "#005777",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#c4e7ff",
        "primary": "#005c55",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#fd761a",
        "primary-container": "#0f766e",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-primary-container": "#a3faef",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#00504a",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#001e2c",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#ffdbca"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "container-margin": "20px",
        "stack-sm": "8px",
        "section-padding": "40px",
        "gutter": "16px",
        "unit": "4px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}